FROM rust:1.83-slim

RUN apt-get update && apt-get install -y binutils && rm -rf /var/lib/apt/lists/*
RUN rustup component add llvm-tools-preview
RUN cargo install cargo-llvm-cov

WORKDIR /app
COPY . .

RUN cargo llvm-cov --workspace --html --output-dir coverage

CMD ["cat", "coverage/index.html"]
