name: Publish docs
on:
  push:
    branches:
      - update-docs
jobs:
  publish_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.9
      - name: run AnnaDB
        run: docker run -d --init -p 10001:10001 -t romanright/annadb:0.2.0
      - name: install poetry
        run: pip install poetry
      - name: install dependencies
        run: poetry install --no-root
        working-directory: docs/docs_gen
      - name: generate docs
        run: poetry run python main.py
        working-directory: docs/docs_gen
      - name: publish docs
        run: bash scripts/publish_docs.sh